// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: supplement.proto

#ifndef PROTOBUF_supplement_2eproto__INCLUDED
#define PROTOBUF_supplement_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_supplement_2eproto();
void protobuf_AssignDesc_supplement_2eproto();
void protobuf_ShutdownFile_supplement_2eproto();

class CMsgSOIDOwner;
class CMsgSOCacheHaveVersion;
class CMsgClientHello;

// ===================================================================

class CMsgSOIDOwner : public ::google::protobuf::Message {
 public:
  CMsgSOIDOwner();
  virtual ~CMsgSOIDOwner();

  CMsgSOIDOwner(const CMsgSOIDOwner& from);

  inline CMsgSOIDOwner& operator=(const CMsgSOIDOwner& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMsgSOIDOwner& default_instance();

  void Swap(CMsgSOIDOwner* other);

  // implements Message ----------------------------------------------

  CMsgSOIDOwner* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CMsgSOIDOwner& from);
  void MergeFrom(const CMsgSOIDOwner& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::uint32 type() const;
  inline void set_type(::google::protobuf::uint32 value);

  // optional uint64 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::uint64 id() const;
  inline void set_id(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:CMsgSOIDOwner)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 id_;
  ::google::protobuf::uint32 type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_supplement_2eproto();
  friend void protobuf_AssignDesc_supplement_2eproto();
  friend void protobuf_ShutdownFile_supplement_2eproto();

  void InitAsDefaultInstance();
  static CMsgSOIDOwner* default_instance_;
};
// -------------------------------------------------------------------

class CMsgSOCacheHaveVersion : public ::google::protobuf::Message {
 public:
  CMsgSOCacheHaveVersion();
  virtual ~CMsgSOCacheHaveVersion();

  CMsgSOCacheHaveVersion(const CMsgSOCacheHaveVersion& from);

  inline CMsgSOCacheHaveVersion& operator=(const CMsgSOCacheHaveVersion& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMsgSOCacheHaveVersion& default_instance();

  void Swap(CMsgSOCacheHaveVersion* other);

  // implements Message ----------------------------------------------

  CMsgSOCacheHaveVersion* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CMsgSOCacheHaveVersion& from);
  void MergeFrom(const CMsgSOCacheHaveVersion& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .CMsgSOIDOwner soid = 1;
  inline bool has_soid() const;
  inline void clear_soid();
  static const int kSoidFieldNumber = 1;
  inline const ::CMsgSOIDOwner& soid() const;
  inline ::CMsgSOIDOwner* mutable_soid();
  inline ::CMsgSOIDOwner* release_soid();
  inline void set_allocated_soid(::CMsgSOIDOwner* soid);

  // optional fixed64 version = 2;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 2;
  inline ::google::protobuf::uint64 version() const;
  inline void set_version(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:CMsgSOCacheHaveVersion)
 private:
  inline void set_has_soid();
  inline void clear_has_soid();
  inline void set_has_version();
  inline void clear_has_version();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::CMsgSOIDOwner* soid_;
  ::google::protobuf::uint64 version_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_supplement_2eproto();
  friend void protobuf_AssignDesc_supplement_2eproto();
  friend void protobuf_ShutdownFile_supplement_2eproto();

  void InitAsDefaultInstance();
  static CMsgSOCacheHaveVersion* default_instance_;
};
// -------------------------------------------------------------------

class CMsgClientHello : public ::google::protobuf::Message {
 public:
  CMsgClientHello();
  virtual ~CMsgClientHello();

  CMsgClientHello(const CMsgClientHello& from);

  inline CMsgClientHello& operator=(const CMsgClientHello& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CMsgClientHello& default_instance();

  void Swap(CMsgClientHello* other);

  // implements Message ----------------------------------------------

  CMsgClientHello* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CMsgClientHello& from);
  void MergeFrom(const CMsgClientHello& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 version = 1;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 1;
  inline ::google::protobuf::uint32 version() const;
  inline void set_version(::google::protobuf::uint32 value);

  // repeated .CMsgSOCacheHaveVersion socache_have_versions = 2;
  inline int socache_have_versions_size() const;
  inline void clear_socache_have_versions();
  static const int kSocacheHaveVersionsFieldNumber = 2;
  inline const ::CMsgSOCacheHaveVersion& socache_have_versions(int index) const;
  inline ::CMsgSOCacheHaveVersion* mutable_socache_have_versions(int index);
  inline ::CMsgSOCacheHaveVersion* add_socache_have_versions();
  inline const ::google::protobuf::RepeatedPtrField< ::CMsgSOCacheHaveVersion >&
      socache_have_versions() const;
  inline ::google::protobuf::RepeatedPtrField< ::CMsgSOCacheHaveVersion >*
      mutable_socache_have_versions();

  // optional uint32 client_session_need = 3;
  inline bool has_client_session_need() const;
  inline void clear_client_session_need();
  static const int kClientSessionNeedFieldNumber = 3;
  inline ::google::protobuf::uint32 client_session_need() const;
  inline void set_client_session_need(::google::protobuf::uint32 value);

  // optional uint32 client_launcher = 4;
  inline bool has_client_launcher() const;
  inline void clear_client_launcher();
  static const int kClientLauncherFieldNumber = 4;
  inline ::google::protobuf::uint32 client_launcher() const;
  inline void set_client_launcher(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:CMsgClientHello)
 private:
  inline void set_has_version();
  inline void clear_has_version();
  inline void set_has_client_session_need();
  inline void clear_has_client_session_need();
  inline void set_has_client_launcher();
  inline void clear_has_client_launcher();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::CMsgSOCacheHaveVersion > socache_have_versions_;
  ::google::protobuf::uint32 version_;
  ::google::protobuf::uint32 client_session_need_;
  ::google::protobuf::uint32 client_launcher_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_supplement_2eproto();
  friend void protobuf_AssignDesc_supplement_2eproto();
  friend void protobuf_ShutdownFile_supplement_2eproto();

  void InitAsDefaultInstance();
  static CMsgClientHello* default_instance_;
};
// ===================================================================


// ===================================================================

// CMsgSOIDOwner

// optional uint32 type = 1;
inline bool CMsgSOIDOwner::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgSOIDOwner::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgSOIDOwner::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgSOIDOwner::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 CMsgSOIDOwner::type() const {
  return type_;
}
inline void CMsgSOIDOwner::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
}

// optional uint64 id = 2;
inline bool CMsgSOIDOwner::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMsgSOIDOwner::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CMsgSOIDOwner::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CMsgSOIDOwner::clear_id() {
  id_ = GOOGLE_ULONGLONG(0);
  clear_has_id();
}
inline ::google::protobuf::uint64 CMsgSOIDOwner::id() const {
  return id_;
}
inline void CMsgSOIDOwner::set_id(::google::protobuf::uint64 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// CMsgSOCacheHaveVersion

// optional .CMsgSOIDOwner soid = 1;
inline bool CMsgSOCacheHaveVersion::has_soid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgSOCacheHaveVersion::set_has_soid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgSOCacheHaveVersion::clear_has_soid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgSOCacheHaveVersion::clear_soid() {
  if (soid_ != NULL) soid_->::CMsgSOIDOwner::Clear();
  clear_has_soid();
}
inline const ::CMsgSOIDOwner& CMsgSOCacheHaveVersion::soid() const {
  return soid_ != NULL ? *soid_ : *default_instance_->soid_;
}
inline ::CMsgSOIDOwner* CMsgSOCacheHaveVersion::mutable_soid() {
  set_has_soid();
  if (soid_ == NULL) soid_ = new ::CMsgSOIDOwner;
  return soid_;
}
inline ::CMsgSOIDOwner* CMsgSOCacheHaveVersion::release_soid() {
  clear_has_soid();
  ::CMsgSOIDOwner* temp = soid_;
  soid_ = NULL;
  return temp;
}
inline void CMsgSOCacheHaveVersion::set_allocated_soid(::CMsgSOIDOwner* soid) {
  delete soid_;
  soid_ = soid;
  if (soid) {
    set_has_soid();
  } else {
    clear_has_soid();
  }
}

// optional fixed64 version = 2;
inline bool CMsgSOCacheHaveVersion::has_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CMsgSOCacheHaveVersion::set_has_version() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CMsgSOCacheHaveVersion::clear_has_version() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CMsgSOCacheHaveVersion::clear_version() {
  version_ = GOOGLE_ULONGLONG(0);
  clear_has_version();
}
inline ::google::protobuf::uint64 CMsgSOCacheHaveVersion::version() const {
  return version_;
}
inline void CMsgSOCacheHaveVersion::set_version(::google::protobuf::uint64 value) {
  set_has_version();
  version_ = value;
}

// -------------------------------------------------------------------

// CMsgClientHello

// optional uint32 version = 1;
inline bool CMsgClientHello::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CMsgClientHello::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CMsgClientHello::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CMsgClientHello::clear_version() {
  version_ = 0u;
  clear_has_version();
}
inline ::google::protobuf::uint32 CMsgClientHello::version() const {
  return version_;
}
inline void CMsgClientHello::set_version(::google::protobuf::uint32 value) {
  set_has_version();
  version_ = value;
}

// repeated .CMsgSOCacheHaveVersion socache_have_versions = 2;
inline int CMsgClientHello::socache_have_versions_size() const {
  return socache_have_versions_.size();
}
inline void CMsgClientHello::clear_socache_have_versions() {
  socache_have_versions_.Clear();
}
inline const ::CMsgSOCacheHaveVersion& CMsgClientHello::socache_have_versions(int index) const {
  return socache_have_versions_.Get(index);
}
inline ::CMsgSOCacheHaveVersion* CMsgClientHello::mutable_socache_have_versions(int index) {
  return socache_have_versions_.Mutable(index);
}
inline ::CMsgSOCacheHaveVersion* CMsgClientHello::add_socache_have_versions() {
  return socache_have_versions_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::CMsgSOCacheHaveVersion >&
CMsgClientHello::socache_have_versions() const {
  return socache_have_versions_;
}
inline ::google::protobuf::RepeatedPtrField< ::CMsgSOCacheHaveVersion >*
CMsgClientHello::mutable_socache_have_versions() {
  return &socache_have_versions_;
}

// optional uint32 client_session_need = 3;
inline bool CMsgClientHello::has_client_session_need() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CMsgClientHello::set_has_client_session_need() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CMsgClientHello::clear_has_client_session_need() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CMsgClientHello::clear_client_session_need() {
  client_session_need_ = 0u;
  clear_has_client_session_need();
}
inline ::google::protobuf::uint32 CMsgClientHello::client_session_need() const {
  return client_session_need_;
}
inline void CMsgClientHello::set_client_session_need(::google::protobuf::uint32 value) {
  set_has_client_session_need();
  client_session_need_ = value;
}

// optional uint32 client_launcher = 4;
inline bool CMsgClientHello::has_client_launcher() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CMsgClientHello::set_has_client_launcher() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CMsgClientHello::clear_has_client_launcher() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void CMsgClientHello::clear_client_launcher() {
  client_launcher_ = 0u;
  clear_has_client_launcher();
}
inline ::google::protobuf::uint32 CMsgClientHello::client_launcher() const {
  return client_launcher_;
}
inline void CMsgClientHello::set_client_launcher(::google::protobuf::uint32 value) {
  set_has_client_launcher();
  client_launcher_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_supplement_2eproto__INCLUDED
